CREATE TABLE "exhibitions" (
    "id" bigserial PRIMARY KEY,
    "title" varchar(30) NOT NULL UNIQUE,
    "title_en" varchar(60) DEFAULT '', 
    "subtitle" varchar(30) DEFAULT '',
    "subtitle_en" varchar(60) DEFAULT '',
    "type"  varchar(20) DEFAULT '',
    "cover" varchar(100) DEFAULT '',
    "start_date" varchar(10) NOT NULL,
    "end_date" varchar(10) DEFAULT '',
    "draft" boolean NOT NULL DEFAULT true,
    "host" varchar(30) NOT NULL,
    "host_en" varchar(60) DEFAULT '',
    "performer" json DEFAULT '{}',
    "location" varchar(30) DEFAULT '',
    "location_en" varchar(60) DEFAULT '',
    "daily_start_time" varchar(5) DEFAULT '',
    "daily_end_time" varchar(5) DEFAULT '',
    "category" varchar(20) NOT NULL DEFAULT '',
    "description" varchar(100) NOT NULL,
    "description_en" varchar(200) DEFAULT '',
    "content" text NOT NULL ,
    "content_en" text DEFAULT '',
    "create_at" bigint NOT NULL,
    "update_at" bigint NOT NULL
);